### ISSUE TITLE
What is the relationship between ModiaBase.jl and Modia.jl?

### ISSUE THREAD

**Issue by metab0t** [ModiaSim/ModiaBase.jl#1]
As the title, I am curious about the relationship between `ModiaBase.jl` and `Modia.jl` which seems stagnant for a while.
Is `ModiaBase.jl` and `TinyModia.jl` designed to replace `Modia.jl` ?

**Comment by HildingElmqvist** [comment]
We are building up an improved code base for Modia since some time. The previous implementation (Modia 0.3) had some drawbacks. For example we wanted to become compatible to DifferentialEquations.jl, Measurements.jl and MonteCarloMeasurements.jl. TinyModia together with ModiaBase does that. Furthermore ModiaBase supports automatic state selection. We organized the code differently, i.e. ModiaBase contains fundamental algorithms. TinyModia does not support events yet and have other limitations. This is why we currently introduced the prefix Tiny.
